# Generated by Django 2.0.1 on 2018-02-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_model_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('channel_id', models.IntegerField()),
                ('mse', models.FloatField()),
                ('utheil', models.FloatField()),
                ('bias', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('version', models.IntegerField()),
                ('status', models.IntegerField()),
                ('alpha', models.FloatField()),
                ('beta', models.FloatField()),
                ('gamma', models.FloatField()),
                ('r_squared', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='forecast date')),
                ('quantity', models.IntegerField(default=0)),
                ('forecast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecaster.Forecast')),
            ],
        ),
        migrations.CreateModel(
            name='Upd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('channel_id', models.IntegerField()),
                ('manual', models.BooleanField()),
                ('upper_limit', models.FloatField()),
                ('lower_limit', models.FloatField()),
                ('forecast', models.BooleanField()),
                ('cv', models.FloatField()),
                ('incidence_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('channel_id', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='forecast date')),
                ('quantity', models.IntegerField(default=0)),
                ('outlier', models.BooleanField()),
                ('manual', models.BooleanField()),
            ],
        ),
    ]
