# Generated by Django 2.0.1 on 2018-02-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0002_auto_20180206_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='alpha',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='beta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='bias',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='mse',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='utheil',
            field=models.FloatField(null=True),
        ),
    ]
