# Generated by Django 2.0.1 on 2018-02-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0003_auto_20180206_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastdetails',
            options={'managed': False},
        ),
    ]
