# Generated by Django 2.0.1 on 2018-02-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0004_auto_20180207_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastdetails',
            options={},
        ),
    ]
