# Generated by Django 2.0.1 on 2018-02-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecaster', '0005_auto_20180207_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_model_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('channel_id', models.IntegerField()),
                ('mse', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utheil', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bias', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('version', models.IntegerField()),
                ('status', models.IntegerField()),
                ('alpha', models.DecimalField(blank=True, decimal_places=14, max_digits=15, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=14, max_digits=15, null=True)),
                ('gamma', models.DecimalField(blank=True, decimal_places=14, max_digits=15, null=True)),
                ('r_squared', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'forecasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'db_table': 'forecasts_details',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='forecastdetails',
            name='forecast_id',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='ForecastDetails',
        ),
    ]
